### ISSUE TITLE
Farben für die Rythmisierung und andere Typen

### ISSUE THREAD

**Issue by tihansen** [WOYM/timetable#188]
Es muss eine Möglichkeit implementiert werden, Farben für Aktivitäten zu vergeben.
Hierbei wird die Rythmisierung von Unterrichten unterschieden, danach haben alle anderen Aktivitätstypen eine eigene Farbe.

An der Farbe selbst muss es eine Ausgabemöglichkeit geben, mit der später eine entsprechende CSS-Klasse am ScheduleModel gesetzt werden kann.

**Comment by tihansen** [comment]
Zu klären wäre, ob dies beim derzeitigen Erzeugen der Aktivitäten direkt beachtet wird (Unit-Tests) und ansonsten, woher diese Farben zum Zeitpunkt der Erzeugung kommen. Konstruktor des Aktivitätsobjektes?

**Comment by alueck** [comment]
Semi erfüllt, da Aktivitätstypen auf GUI-Ebene noch keine Farben zugeordnet werden können, daher nochmal geöffnet.
