### ISSUE TITLE
Einstellung, welche Wochentage zu verplanen sind

### ISSUE THREAD

**Issue by tihansen** [WOYM/timetable#190]
Es muss einstellbar sein, ob Samstag und Sonntag angezeigt werden.

**Comment by alueck** [comment]
Allgemeine Einstellung, welche Wochentage zu verplanen sind. Wenn Sa/So nicht gewählt, werden sie ausgeblendet, für alle anderen Tage wird die Erstellung von Aktivitäten unterbunden, wenn sie nicht ausgewählt wurden.
