### ISSUE TITLE
Überprüfung auf Überschneidungen mit Aktivitäten von Mitarbeitern

### ISSUE THREAD

**Issue by alueck** [WOYM/timetable#224]
Beim Hinzufügen einer Aktivität muss geprüft werden, ob sich TimePeriod-Objekte der enthaltenen EmployeeTimePeriods-Objekte mit vorhandenen Aktivitäten bei den Mitarbeitern überschneiden. Damit das ganze zumindest etwas schneller geht, kann die getAllActivities(Employee, Weekday) Methode verwendet werden, um nur Aktivitäten für den entsprechenden Wochentag aus der DB zu holen.

**Comment by JurSch** [comment]
Die komplette Validierung muss angepasst werden zurzeit ist nicht das Komplette gewünschte verhalten enthalten.
