### ISSUE TITLE
TimePeriod Objekte Validierung erweitern

### ISSUE THREAD

**Issue by JurSch** [WOYM/timetable#231]
Zurzeit ist es möglich Zeiten außerhalb der Gesetzten grenzen zu wählen . Das soll unterbunden werden. Weiterhin kann die Endzeit vor die Startzeit durch die Abzüge seiten der Zieh-Funktion der GUI erreicht werden.

**Comment by tihansen** [comment]
Im Dialog zum Hinzufügen von Aktivitäten werden diese Grenzen bereits beachtet!

**Comment by JurSch** [comment]
Fehlverhlaten wurde aufgetan, wieses wurde mit PR #270 behoben
