### ISSUE TITLE
Ungültige Zeit über TimePicker im Aktivitätendialog wählbar

### ISSUE THREAD

**Issue by alueck** [WOYM/timetable#281]
Sei das Ende eines Wochentages in den Einstellungen auf 16 Uhr festgelegt: Öffnet man nun den Dialog zum Hinzufügen einer Aktivität und wählt für die Endzeit die maximale Stunden-und Minutenzahl aus, erhält man bei einem Zeitraster von 15 Minuten eine Endzeit von 16:45, die außerhalb der Einstellungen liegt.

**Comment by JurSch** [comment]
sollte es dafür keine schnelle lösung optischer natur geben kann die methode isTimeInRange() des PlanningControlles genommen werden

**Comment by tihansen** [comment]
Es wurde die Endzeit für die Maximalstundenzahl verwendet. Diese wird nun um 1 verringert.
